-- ============================================================================
-- Datos iniciales para H2 (perfil dev)
-- Ejecutado automáticamente por Quarkus con strategy: drop-and-create
-- 70 Personas (P) + 30 Organizaciones (O)
-- ============================================================================

-- PERSONAS NATURALES (P) — DNI Nacionales
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '10301554', 'Carlos', 'García', 'López', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '45678912', 'María Elena', 'Rodríguez', 'Fernández', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '72345678', 'José Luis', 'Martínez', 'Huamán', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '80123456', 'Ana Patricia', 'Quispe', 'Mamani', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '43216789', 'Pedro', 'Flores', 'Castillo', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '65432198', 'Rosa María', 'Torres', 'Díaz', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '78901234', 'Miguel Ángel', 'Vargas', 'Rojas', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '34567890', 'Lucía', 'Mendoza', 'Paredes', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '56789012', 'Fernando', 'Sánchez', 'Gutiérrez', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '12345679', 'Carmen Rosa', 'Chávez', 'Morales', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '23456781', 'Roberto', 'Espinoza', 'Ramos', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '34567892', 'Silvia', 'Cabrera', 'Vega', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '45678903', 'Juan Carlos', 'Palacios', 'Herrera', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '56789014', 'Gladys', 'Córdova', 'Tapia', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '67890125', 'Raúl', 'Huamán', 'Quispe', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '78901236', 'Teresa', 'Aguilar', 'Salazar', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '89012347', 'Óscar', 'Peña', 'Campos', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '90123458', 'Patricia', 'Rivera', 'Reyes', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '11234567', 'Andrés', 'Villavicencio', 'Medina', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '22345678', 'Juana', 'Contreras', 'Delgado', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '33456789', 'Luis Alberto', 'Romero', 'Navarro', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '44567890', 'Beatriz', 'Pariona', 'Zúñiga', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '55678901', 'Ricardo', 'Cárdenas', 'Vera', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '66789012', 'Margarita', 'Bazán', 'Ortega', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '77890123', 'Hugo', 'Valverde', 'Arias', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '88901234', 'Cecilia', 'Montes', 'Carrasco', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '99012345', 'Enrique', 'Lozano', 'Figueroa', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '10234567', 'Norma', 'Benítez', 'Cáceres', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '21345678', 'Víctor', 'Choque', 'Ticona', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '32456789', 'Isabel', 'Apaza', 'Condori', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '43567890', 'Alberto', 'Guzmán', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '54678901', 'Mónica', 'Zavala', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '65789012', 'Julio César', 'Bustamante', 'Oliva', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '76890123', 'Pilar', 'Ccama', 'Huanca', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '87901234', 'Santiago', 'Atahuachi', 'Puma', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '98012345', 'Doris', 'Yupanqui', 'Inga', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '19123456', 'Alfredo', 'Obando', 'Tejada', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '20234567', 'Elena', 'Valdivia', 'Cueva', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '31345678', 'Marco Antonio', 'Pacheco', 'Soto', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '42456789', 'Graciela', 'Suárez', 'Aliaga', NULL, 'P', 'N', NOW(), NOW());

-- DNI - Nacionales sin apellido materno
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '53567890', 'Domingo', 'Tello', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '64678901', 'Consuelo', 'Arce', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '75789012', 'Ernesto', 'Meza', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '86890123', 'Adelina', 'Pillco', NULL, NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('1', '97901234', 'Héctor', 'Ríos', NULL, NULL, 'P', 'N', NOW(), NOW());

-- Carné de Extranjería - Extranjeros
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2023000001', 'Alejandro', 'Pérez', 'Gómez', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2023000002', 'Valentina', 'Muñoz', 'Herrera', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2023000003', 'Sebastián', 'Ramírez', 'Varela', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2023000004', 'Camila', 'Orozco', 'Duarte', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2023000005', 'Mateo', 'Londoño', 'Ríos', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2024000001', 'Isabella', 'Cardona', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2024000002', 'Daniel', 'Aristizábal', 'Mesa', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2024000003', 'Luciana', 'Echeverría', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2024000004', 'Andrés Felipe', 'Betancourt', 'Osorio', NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('3', 'CE2024000005', 'Mariana', 'Saldarriaga', 'Correa', NULL, 'P', 'E', NOW(), NOW());

-- Pasaporte - Extranjeros
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'AB12345678', 'James', 'Smith', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'CD98765432', 'Sophie', 'Müller', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'EF11223344', 'Takeshi', 'Yamamoto', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'GH55667788', 'Marie Claire', 'Dubois', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'IJ99001122', 'Giovanni', 'Rossi', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'KL33445566', 'Chen Wei', 'Zhang', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'MN77889900', 'Priya', 'Sharma', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'OP12349876', 'Hans', 'Schneider', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'QR56781234', 'Yoon-Seo', 'Park', NULL, NULL, 'P', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('4', 'ST90125678', 'Fatima', 'Al-Rashid', NULL, NULL, 'P', 'E', NOW(), NOW());

-- Carné de Identidad - Menores nacionales
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('2', 'CI20230001', 'Matías', 'García', 'Torres', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('2', 'CI20230002', 'Valentina', 'Quispe', 'Flores', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('2', 'CI20230003', 'Thiago', 'Rodríguez', 'Mamani', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('2', 'CI20230004', 'Mía', 'Huamán', 'López', NULL, 'P', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('2', 'CI20230005', 'Liam', 'Martínez', 'Chávez', NULL, 'P', 'N', NOW(), NOW());

-- ORGANIZACIONES (O) — RUC Nacionales con trade_name
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100130204', 'Banco de Crédito del Perú S.A.', NULL, NULL, 'BCP', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100047218', 'Banco Internacional del Perú S.A.A.', NULL, NULL, 'Interbank', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100055237', 'Scotiabank Perú S.A.A.', NULL, NULL, 'Scotiabank', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100043140', 'BBVA Continental S.A.', NULL, NULL, 'BBVA', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20418896915', 'Telefónica del Perú S.A.A.', NULL, NULL, 'Movistar', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100128056', 'Alicorp S.A.A.', NULL, NULL, 'Alicorp', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100127912', 'Unión de Cervecerías Peruanas Backus y Johnston', NULL, NULL, 'Backus', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100154308', 'Southern Peru Copper Corporation', NULL, NULL, 'Southern Copper', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100116635', 'Cementos Pacasmayo S.A.A.', NULL, NULL, 'Pacasmayo', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20330791412', 'Saga Falabella S.A.', NULL, NULL, 'Falabella', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20109072177', 'Cencosud Retail Perú S.A.', NULL, NULL, 'Wong', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20492092313', 'Supermercados Peruanos S.A.', NULL, NULL, 'Plaza Vea', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100190797', 'Gloria S.A.', NULL, NULL, 'Gloria', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20100152356', 'Entel Perú S.A.', NULL, NULL, 'Entel', 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20505072702', 'Latam Airlines Perú S.A.', NULL, NULL, 'Latam', 'O', 'N', NOW(), NOW());

-- RUC - Organizaciones nacionales sin trade_name
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20601327318', 'Soluciones Digitales del Perú S.A.C.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20602415679', 'Consultora Andina de Negocios S.R.L.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20603512890', 'Importadora del Pacífico E.I.R.L.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20604678123', 'Constructora Los Andes S.A.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20605789234', 'Agroindustrias del Sur S.A.C.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20606890345', 'Transportes Unidos del Norte S.R.L.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20607901456', 'Laboratorio Farmacéutico Nacional S.A.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20608012567', 'Minera Cordillera Blanca S.A.C.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20609123678', 'Textiles Finos del Perú S.A.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20610234789', 'Grupo Gastronómico Limeño S.A.C.', NULL, NULL, NULL, 'O', 'N', NOW(), NOW());

-- RUC - Organizaciones extranjeras
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20501523837', 'Microsoft Perú S.R.L.', NULL, NULL, 'Microsoft', 'O', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20503837219', 'Amazon Web Services Perú S.R.L.', NULL, NULL, 'AWS', 'O', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20506478301', 'Google Cloud Perú S.A.C.', NULL, NULL, 'Google Cloud', 'O', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20508912456', 'SAP Perú S.R.L.', NULL, NULL, 'SAP', 'O', 'E', NOW(), NOW());
INSERT INTO customers (document_type, document_number, name, paternal_surname, maternal_surname, trade_name, customer_type, residency_status, created_at, updated_at) VALUES ('6', '20510345678', 'Oracle del Perú S.R.L.', NULL, NULL, 'Oracle', 'O', 'E', NOW(), NOW());
